Update workflow to generate new variants file

diff --git a/.github/workflows/compile-rtk-everywhere.yml b/.github/workflows/compile-rtk-everywhere.yml
--- a/.github/workflows/compile-rtk-everywhere.yml
+++ b/.github/workflows/compile-rtk-everywhere.yml
@@ -104,7 +104,7 @@ jobs:
         with:
           source_file: ./Firmware/build/${{ env.FILENAME_PREFIX }}${{ env.FILE_ENDING_UNDERSCORE }}.bin
           destination_repo: 'sparkfun/SparkFun_RTK_Everywhere_Firmware_Binaries'
-          destination_folder: ''
+          destination_folder: 'soc/esp32'
           user_email: 'nathan@sparkfun.com'
           user_name: 'nseidle'
           commit_message: 'Github Action - Updating Binary ${{ steps.dateNoScores.outputs.dateNoScores }}'
@@ -115,7 +115,65 @@ jobs:
           path: ${{ env.JSON_FILE_NAME }}
           write-mode: overwrite
           contents: |
-            {"Configurations": [{"Version":"${{ env.FIRMWARE_VERSION_MAJOR }}.${{ env.FIRMWARE_VERSION_MINOR }}${{ env.JSON_ENDING }}", "URL":"https://raw.githubusercontent.com/sparkfun/SparkFun_RTK_Everywhere_Firmware_Binaries/main/${{ env.FILENAME_PREFIX }}${{ env.FILE_ENDING_UNDERSCORE }}.bin"}]}
+            {"Configurations": [{"Version":"${{ env.FIRMWARE_VERSION_MAJOR }}.${{ env.FIRMWARE_VERSION_MINOR }}${{ env.JSON_ENDING }}", "URL":"https://raw.githubusercontent.com/sparkfun/SparkFun_RTK_Everywhere_Firmware_Binaries/main/soc/esp32/${{ env.FILENAME_PREFIX }}${{ env.FILE_ENDING_UNDERSCORE }}.bin"}]}
+
+      # Mimics Release_Firmware.sh (main) and RC_Firmware.sh (other branches)
+      - name: Update RTK-Everywhere-Variants.csv
+        run: |
+          set -e
+          CSV_FILE=RTK-Everywhere-Variants.csv
+          BIN_NAME=${{ env.FILENAME_PREFIX }}${{ env.FILE_ENDING_UNDERSCORE }}.bin
+          BIN_FILE=./Firmware/build/$BIN_NAME
+          MAJOR=${{ env.FIRMWARE_VERSION_MAJOR }}
+          MINOR=${{ env.FIRMWARE_VERSION_MINOR }}
+
+          # Build the CRC tool
+          make -C ./Firmware/Tools File_CRC
+
+          # Get the most recent file. Use the API, raw.githubusercontent.com caches for up to 5 minutes
+          curl --fail --silent --show-error --location \
+            --header "Accept: application/vnd.github.raw" \
+            --output $CSV_FILE \
+            https://api.github.com/repos/sparkfun/SparkFun_RTK_Everywhere_Firmware_Binaries/contents/$CSV_FILE
+          head -n 1 $CSV_FILE | grep -q "^model,subsystem,chip," || { echo "ERROR: Unexpected CSV contents"; cat $CSV_FILE; exit 1; }
+
+          # Make sure the file ends with a newline before appending
+          sed -i -e '$a\' $CSV_FILE
+
+          if [[ $BRANCH == 'main' ]]; then
+              # Remove the latest release lines, remember v3.4 uses ESP32,ESP32 instead of SOC,ESP32
+              awk -F, '!($1 == "*" && ($2 == "SOC" || $2 == "ESP32") && $3 == "ESP32" && $8 == "0")' $CSV_FILE > $CSV_FILE.tmp
+              mv $CSV_FILE.tmp $CSV_FILE
+
+              # Append the ESP32,ESP32 release line for v3.4
+              ./Firmware/Tools/File_CRC $BIN_FILE "*,ESP32,ESP32,$MAJOR,$MINOR,0,0,0,soc/esp32/$BIN_NAME" >> $CSV_FILE
+
+              # Append the SOC,ESP32 release line for > v3.4
+              ./Firmware/Tools/File_CRC $BIN_FILE "*,SOC,ESP32,$MAJOR,$MINOR,0,0,0,$BIN_NAME" >> $CSV_FILE
+          else
+              # Remove the release candidate (RC) line
+              awk -F, '!($1 == "*" && $2 == "SOC" && $3 == "ESP32" && $8 == "1")' $CSV_FILE > $CSV_FILE.tmp
+              mv $CSV_FILE.tmp $CSV_FILE
+
+              # Append the new SOC,ESP32 release candidate line
+              ./Firmware/Tools/File_CRC $BIN_FILE "*,SOC,ESP32,$MAJOR,$MINOR,0,0,1,$BIN_NAME" >> $CSV_FILE
+          fi
+
+          # Display the updated file
+          cat $CSV_FILE
+
+      - name: Push CSV to Binaries Repo
+        # uses: dmnemec/copy_file_to_another_repo_action #Workaround for Issue: https://github.com/orgs/community/discussions/55820#discussioncomment-5946136
+        uses: Jason2866/copy_file_to_another_repo_action@http408_fix
+        env:
+          API_TOKEN_GITHUB: ${{ secrets.PUSH_BINARIES_REPO }}
+        with:
+          source_file: RTK-Everywhere-Variants.csv
+          destination_repo: 'sparkfun/SparkFun_RTK_Everywhere_Firmware_Binaries'
+          destination_folder: ''
+          user_email: 'nathan@sparkfun.com'
+          user_name: 'nseidle'
+          commit_message: 'Github Action - Updating CSV ${{ steps.dateNoScores.outputs.dateNoScores }}'
 
       - name: Push JSON to Binaries Repo
         # uses: dmnemec/copy_file_to_another_repo_action #Workaround for Issue: https://github.com/orgs/community/discussions/55820#discussioncomment-5946136
